### ISSUE TITLE
Master Password Configuration

### ISSUE THREAD

**Issue by ibaraki-douji** [EvoTM/docker-trackmania#24]
Hello,

So i just started to create a server but when i try to put the master password it changes to another thing with `&amp;` and removing some parts.
![image](https://user-images.githubusercontent.com/72337875/188462289-3fe594d6-5178-4d0d-b275-b70289394002.png)
So i'm unable to launch the server without a HTTP 401 error.

**Comment by Chris92de** [comment]
Yes, that is unfortunately a problem with some of the passwords the Trackmania Player page assigns.
The only workaround is to delete the dedicated server account and make a new one and hope you get a better password that doesn't break Docker.

**Comment by ibaraki-douji** [comment]
OK ok
