### ISSUE TITLE
Join URL does not seem to have an effect

### ISSUE THREAD

**Issue by Slluxx** [EvoTM/docker-trackmania#30]
Can one join with the free version of the game or is club needed?
Currently, it just throws me into the main menu

**Comment by Chris92de** [comment]
Hello, the join URL only works for people with Standard and Club Access.
Please refer to https://www.trackmania.com/detailed-offers of what you can do with each version of the game.

Also, this repository is community-run and not officially endorsed by nor affiliated with the developers of Trackmania at Ubisoft Nadeo.
